/** Keynote shell: full-size computational stage, separate library, contextual tools. */
const icons: Record<string,string> = {
 library:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
 inspect:'<path d="M4 4h16v16H4zM14 4v16M17 8h1M17 12h1"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',plus:'<path d="M12 5v14M5 12h14"/>',minus:'<path d="M5 12h14"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
};
const icon=(name:string)=>`<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name]}</svg>`;
export function installAppearance() {
 const header=document.querySelector('header')!;header.querySelector('.version')?.remove();
 const actions=document.createElement('nav');actions.className='header-actions';actions.setAttribute('aria-label','工作台');
 actions.innerHTML=`<span id="connection-state" class="connection-indicator" data-state="idle">本地演示</span><button id="catalog-toggle" aria-controls="model-library" aria-expanded="false">${icon('library')}模型库</button><button id="inspector-toggle" aria-controls="model-inspector" aria-expanded="false">${icon('inspect')}解读与参数</button><button id="presentation" aria-pressed="false">演示模式</button>`;header.append(actions);
 const aside=document.querySelector('aside')!;aside.id='model-library';
 const inspector=document.querySelector<HTMLElement>('.inspector')!;inspector.id='model-inspector';
 const detailBody=document.createElement('section');detailBody.className='inspector-explanation';while(inspector.firstChild)detailBody.append(inspector.firstChild);
 const inspectorHeader=document.createElement('div');inspectorHeader.className='inspector-header';inspectorHeader.innerHTML=`<h2>模型解读</h2><button id="inspector-close" aria-label="关闭解读面板">${icon('close')}</button>`;inspector.append(inspectorHeader,detailBody);
 const index=aside.querySelector('.index')!,params=aside.querySelector('#params')!,tensorDetails=aside.querySelector('#tensor-select')!.closest('details')!;inspector.append(index,params,tensorDetails);
 const libraryContent=document.createElement('div');libraryContent.className='library-connection';while(aside.firstChild)libraryContent.append(aside.firstChild);
 const libraryHero=document.createElement('div');libraryHero.className='library-hero';libraryHero.innerHTML='<h2>让代码，<br><em>显形。</em></h2><p>从一个神经元，走进模型的内部。<br>选择架构，或连接你正在编写的 PyTorch 模型。</p><button id="library-return">返回当前模型 '+icon('arrow')+'</button>';
 const families=[
  {name:'基础网络',en:'Foundations',desc:'从权重到感受野，逐个元素理解计算。',kind:'dense',models:[['declarative','可调 MLP'],['mlp','PyTorch MLP'],['conv2d','残差卷积'],['conv3d','3D 卷积']]},
  {name:'注意力与语言',en:'Attention',desc:'跟随 Token，观察投影、注意力与特征汇聚。',kind:'attention',models:[['official_llama','原生 LLaMA'],['tinygpt','TinyGPT'],['transformer','Transformer'],['attention','基础注意力'],['llama','LLaMA-style']]},
  {name:'变分自编码',en:'Latent space',desc:'编码分布、真实采样、解码重建。',kind:'vae',models:[['official_vae','PyTorch 官方 VAE'],['conv_vae','卷积 VAE'],['conditional_vae','条件 VAE']]},
  {name:'集合架构',en:'Set learning',desc:'从作者实现理解 SAB 与诱导点注意力。',kind:'set',models:[['official_sab','作者 SAB'],['official_isab','作者 ISAB'],['sab','SAB 测试模型'],['isab','ISAB 测试模型']]},
 ];
 const libraryFamilies=document.createElement('div');libraryFamilies.className='library-families';
 for(const f of families){const d=document.createElement('details');d.className=`model-family ${f.kind}`;d.open=f.kind==='vae';d.innerHTML=`<summary><span class="family-diagram" aria-hidden="true">${familyDiagram(f.kind)}</span><span><strong>${f.name}</strong><small>${f.en}</small></span><span class="family-expand">${icon('plus')}</span></summary><div class="family-content"><p>${f.desc}</p><div>${f.models.map(([id,label])=>`<button data-model="${id}">${label}${icon('arrow')}</button>`).join('')}</div></div>`;libraryFamilies.append(d);}
 aside.append(libraryHero,libraryFamilies,libraryContent);
 const workspace=document.querySelector<HTMLElement>('.workspace')!,controls=workspace.querySelector('.controls')!,timeline=workspace.querySelector('.timeline')!,status=workspace.querySelector('.status')!;
 const dock=document.createElement('div');dock.className='stage-dock';dock.append(controls,timeline,status);workspace.append(dock);workspace.querySelector('.toolbar')!.append(workspace.querySelector('.navigation')!);
 document.querySelector('#zoom-in')!.innerHTML=icon('plus');document.querySelector('#zoom-out')!.innerHTML=icon('minus');
 const legend=document.querySelector('.legend')!,legendPanel=document.createElement('details');legendPanel.className='color-key';legendPanel.innerHTML='<summary>数值色谱</summary>';legend.replaceWith(legendPanel);legendPanel.append(legend);inspector.append(legendPanel);
 const statistics=document.querySelector('#stats')!,stats=document.createElement('details');stats.className='render-stats';stats.innerHTML='<summary>渲染信息</summary>';statistics.replaceWith(stats);stats.append(statistics);inspector.append(stats);
 const catalog=document.querySelector<HTMLButtonElement>('#catalog-toggle')!,presentation=document.querySelector<HTMLButtonElement>('#presentation')!,inspect=document.querySelector<HTMLButtonElement>('#inspector-toggle')!;
 let catalogOpen=false,inspectorOpen=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 function sync(){const presenting=presentation.getAttribute('aria-pressed')==='true';document.body.dataset.presentation=String(presenting);document.body.dataset.catalog=catalogOpen?'open':'closed';document.body.dataset.inspector=String(inspectorOpen&&!presenting&&!catalogOpen);catalog.setAttribute('aria-expanded',String(catalogOpen));inspect.setAttribute('aria-expanded',String(inspectorOpen&&!presenting&&!catalogOpen));presentation.textContent=presenting?'退出演示':'演示模式';aside.hidden=!catalogOpen;inspector.hidden=!inspectorOpen||presenting||catalogOpen;workspace.inert=catalogOpen;}
 function revealStage(){catalogOpen=false;sync();modelEntrance(document.querySelector('#stage') as HTMLElement);}
 catalog.onclick=()=>{catalogOpen=!catalogOpen;presentation.setAttribute('aria-pressed','false');sync();if(catalogOpen&&!reduced.matches)aside.animate([{opacity:.4,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}],{duration:480,easing:'cubic-bezier(.16,1,.3,1)'});};
 inspect.onclick=()=>{catalogOpen=false;presentation.setAttribute('aria-pressed','false');inspectorOpen=!inspectorOpen;sync();};
 document.querySelector<HTMLButtonElement>('#inspector-close')!.onclick=()=>{inspectorOpen=false;sync();inspect.focus();};document.querySelector<HTMLButtonElement>('#library-return')!.onclick=revealStage;
 presentation.onclick=()=>{catalogOpen=false;presentation.setAttribute('aria-pressed',String(presentation.getAttribute('aria-pressed')!=='true'));sync();};document.addEventListener('keydown',e=>{if(e.key==='Escape'){catalogOpen=false;inspectorOpen=false;presentation.setAttribute('aria-pressed','false');sync();}});
 libraryFamilies.querySelectorAll<HTMLButtonElement>('[data-model]').forEach(button=>button.onclick=()=>{const select=document.querySelector<HTMLSelectElement>('#example')!;select.value=button.dataset.model!;select.dispatchEvent(new Event('change',{bubbles:true}));revealStage();});
 const imported=document.querySelector<HTMLLabelElement>('label[for=file]')!;imported.tabIndex=0;imported.setAttribute('role','button');imported.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();document.querySelector<HTMLInputElement>('#file')!.click();}};document.querySelector('#file')!.addEventListener('change',revealStage);
 const live=document.querySelector('#live-status')!,indicator=document.querySelector<HTMLElement>('#connection-state')!;new MutationObserver(()=>{const text=live.textContent??'';indicator.dataset.state=/失败|重试/.test(text)?'error':/已连接/.test(text)?'ready':/捕获|等待/.test(text)?'loading':'idle';indicator.textContent=indicator.dataset.state==='ready'?'IDE 已连接':indicator.dataset.state==='loading'?'正在连接':indicator.dataset.state==='error'?'连接待处理':'本地演示';}).observe(live,{childList:true,characterData:true,subtree:true});
 const hidden=()=>document.body.dataset.hidden=String(document.hidden);document.addEventListener('visibilitychange',hidden);hidden();sync();
}
function familyDiagram(kind:string){let paths='';if(kind==='dense'||kind==='set'){for(let i=0;i<4;i++)for(let j=0;j<4;j++)paths+=`<path d="M${10+i*12} 12 ${20+j*8} 40" opacity=".3"/>`;for(let i=0;i<4;i++)paths+=`<rect x="${7+i*12}" y="6" width="6" height="6"/><rect x="${17+i*8}" y="40" width="6" height="6"/>`;}else if(kind==='vae'){paths='<path d="M8 12 26 25 8 44M56 12 38 25 56 44"/><ellipse cx="32" cy="27" rx="9" ry="16"/><ellipse cx="32" cy="27" rx="18" ry="8"/><circle cx="32" cy="27" r="3"/>';}else{for(let i=0;i<4;i++)for(let j=0;j<4;j++)paths+=`<rect x="${12+i*10}" y="${7+j*10}" width="7" height="7" opacity="${.2+(i===j?.8:.1*j)}"/>`;}return `<svg viewBox="0 0 64 54" fill="none" stroke="currentColor" stroke-width="1">${paths}</svg>`;}
export function modelEntrance(stage:HTMLElement) {if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;stage.getAnimations().forEach(a=>a.cancel());stage.animate([{opacity:.5,filter:'blur(4px)',transform:'scale(.985)'},{opacity:1,filter:'blur(0)',transform:'scale(1)'}],{duration:800,easing:'cubic-bezier(.16,1,.3,1)'});}
